### ISSUE TITLE
Requesting access for the Gigantum LabManager

### ISSUE THREAD

**Issue by gkiar** [gigantum/gigantum-cli#3]
Hi!

I'd like to have access to the Docker LabManager container (advertised by `gigantum install` to live here: https://hub.docker.com/r/gigantum/labmanager/). Below are my questions 3:

 - What must one do to be considered for the closed alpha?
 - Is there a protocol for requesting access that I missed in the docs, other than just pinging you here?
 - Will the container be made public after the closed alpha? If not, will building it locally from the Git repo allow a not-logged-in system to proceed with `gigantum install`?

Also, my Docker hub handle is `gkiar`.

Thanks for your support and the cool looking project!!

**Comment by dkleissa** [comment]
Yes things will be made public once we roll out of this closed testing period (and installed through a slightly different process). I'll shoot you an email and take this offline.
