### ISSUE TITLE
Implicitly call install when starting

### ISSUE THREAD

**Issue by billvb** [gigantum/gigantum-cli#50]
Currently, the workflow to install Gigantum from the cli is
```
(1) pip install gigantum
(2) gigantum install
(3) gigantum start
```

It would be great to remove the middle step and have it implicitly install when starting (perhaps with some kind of indication that initial start-up may take some more time).

Ultimately, it would be nice if getting Gigantum up and running is as simple as:

```
pip install gigantum
gigantum start
```

**Comment by tylercasablanca** [comment]
Seems like a no brainer and if they do it then they've got to pay the time penalty anyways, so we should do this.
